import { useState } from "react";
import { Share2, Copy, CheckCircle, X } from "lucide-react";
import { formatINR } from "../utils/formatCurrency";

export default function ShareWhatsApp({ result, input }) {
  const [open, setOpen] = useState(false);
  const [copied, setCopied] = useState(false);

  if (!result) return null;

  const PHONE = "919876543210";

  const buildMessage = () => {
    return `🛡️ *Insurance Premium Quote — InsurePredict*

📋 *My Profile:*
- Age: ${input?.age} years
- Gender: ${input?.sex === "male" ? "Male" : "Female"}
- BMI: ${input?.bmi}
- Smoker: ${input?.smoker ? "Yes 🚬" : "No ✅"}
- Insurance Type: ${input?.insurance_type?.toUpperCase()}

💰 *Premium Result:*
- Annual Premium: *${formatINR(result.predicted_premium)}*
- Range: ${formatINR(result.confidence_range?.min)} – ${formatINR(result.confidence_range?.max)}
- Risk Score: ${result.risk_score}/100 (${result.risk_level} Risk)

📦 *Best Plan for Me:*
- Basic: ${formatINR(result.plan_comparison?.basic?.premium)}
- Standard: ${formatINR(result.plan_comparison?.standard?.premium)} ⭐
- Premium: ${formatINR(result.plan_comparison?.premium?.premium)}

💡 *Recommendation:*
${result.recommendation}

🔗 Get your free quote: http://localhost:5173/predict

_Generated by InsurePredict — Smart Insurance Calculator_`;
  };

  const shareOnWhatsApp = (direct = false) => {
    const msg = buildMessage();
    const phone = direct ? PHONE : "";
    const url = phone
      ? `https://wa.me/${phone}?text=${encodeURIComponent(msg)}`
      : `https://wa.me/?text=${encodeURIComponent(msg)}`;
    window.open(url, "_blank");
    setOpen(false);
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(buildMessage());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <>
      <button
        onClick={() => setOpen(true)}
        className="flex items-center gap-2 bg-green-500 hover:bg-green-600
                   text-white font-semibold px-5 py-3 rounded-2xl
                   transition shadow-lg shadow-green-100"
      >
        <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">
          <path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 00-3.48-8.413z" />
        </svg>
        Share on WhatsApp
      </button>

      {open && (
        <div
          className="fixed inset-0 bg-black/50 flex items-center
                        justify-center z-50 px-4"
        >
          <div
            className="bg-white rounded-3xl w-full max-w-md
                          shadow-2xl overflow-hidden"
          >
            <div
              className="bg-linear-to-r from-green-500 to-green-600
                            p-5 text-white"
            >
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-3">
                  <div
                    className="w-10 h-10 bg-white/20 rounded-xl
                                  flex items-center justify-center"
                  >
                    <Share2 className="w-5 h-5" />
                  </div>
                  <div>
                    <h3 className="font-bold">Share Your Quote</h3>
                    <p className="text-xs text-green-100">
                      Share via WhatsApp or copy text
                    </p>
                  </div>
                </div>
                <button
                  onClick={() => setOpen(false)}
                  className="w-8 h-8 bg-white/20 rounded-full flex
                             items-center justify-center hover:bg-white/30
                             transition"
                >
                  <X className="w-4 h-4" />
                </button>
              </div>
            </div>

            <div className="p-5">
              <p className="text-xs font-semibold text-gray-500 mb-2">
                PREVIEW
              </p>
              <div
                className="bg-green-50 border border-green-100
                              rounded-2xl p-4 mb-5 max-h-48
                              overflow-y-auto"
              >
                <pre
                  className="text-xs text-gray-700 whitespace-pre-wrap
                                font-sans leading-relaxed"
                >
                  {buildMessage()}
                </pre>
              </div>

              <div className="flex flex-col gap-3">
                <button
                  onClick={() => shareOnWhatsApp(false)}
                  className="flex items-center gap-3 bg-green-500
                             hover:bg-green-600 text-white font-semibold
                             px-5 py-3.5 rounded-2xl transition
                             shadow-lg shadow-green-100"
                >
                  <svg
                    className="w-5 h-5 shrink-0"
                    fill="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 00-3.48-8.413z" />
                  </svg>
                  <div className="text-left">
                    <p className="text-sm">Share to Anyone on WhatsApp</p>
                    <p className="text-xs text-green-100">
                      Opens WhatsApp contact picker
                    </p>
                  </div>
                </button>

                <button
                  onClick={() => shareOnWhatsApp(true)}
                  className="flex items-center gap-3 bg-white
                             border-2 border-green-200 hover:bg-green-50
                             text-green-700 font-semibold px-5 py-3.5
                             rounded-2xl transition"
                >
                  <svg
                    className="w-5 h-5 shrink-0 text-green-600"
                    fill="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 00-3.48-8.413z" />
                  </svg>
                  <div className="text-left">
                    <p className="text-sm">Send to InsurePredict Agent</p>
                    <p className="text-xs text-green-500">
                      Get expert advice on your quote
                    </p>
                  </div>
                </button>

                <button
                  onClick={copyToClipboard}
                  className="flex items-center gap-3 bg-gray-50
                             border border-gray-200 hover:bg-gray-100
                             text-gray-700 font-semibold px-5 py-3.5
                             rounded-2xl transition"
                >
                  {copied ? (
                    <CheckCircle
                      className="w-5 h-5 text-green-500
                                              shrink-0"
                    />
                  ) : (
                    <Copy
                      className="w-5 h-5 text-gray-400
                                              shrink-0"
                    />
                  )}
                  <div className="text-left">
                    <p className="text-sm">
                      {copied ? "Copied! ✅" : "Copy to Clipboard"}
                    </p>
                    <p className="text-xs text-gray-400">
                      Paste anywhere you want
                    </p>
                  </div>
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </>
  );
}
